export interface Env {
  DB: D1Database;

  // Cloudflare 静态资源绑定，用于 SPA fallback 返回 index.html。
  ASSETS?: Fetcher;

  // 可选的内部自服务绑定（由 CI 部署配置）。
  SELF?: Fetcher;

  // 可选的仅开发环境使用的追踪密钥。设置后，仅当调用方提供
  // `X-Uptimer-Trace-Token` 时才会处理追踪头。
  UPTIMER_TRACE_TOKEN?: string;
  TRACE_TOKEN?: string;
  UPTIMER_HOMEPAGE_RESIDUAL_TRACE?: string;
  UPTIMER_SCHEDULED_STATUS_REFRESH?: string;
  UPTIMER_TRACE_TIMINGS?: string;
  UPTIMER_HOMEPAGE_RELEASE_LOCK?: string;
  UPTIMER_HOMEPAGE_WRITE_LEASE_CHECK?: string;
  UPTIMER_PUBLIC_MONITOR_FRAGMENT_WRITES?: string;
  UPTIMER_PUBLIC_MONITOR_UPDATE_FRAGMENT_WRITES?: string;
  UPTIMER_PUBLIC_SHARDED_HOMEPAGE_RUNTIME_SEED?: string;
  UPTIMER_MONITOR_RUNTIME_UPDATE_FRAGMENT_MAX_AGE_SECONDS?: string;
  UPTIMER_SCHEDULED_RUNTIME_FRAGMENT_REFRESH?: string;
  UPTIMER_SHARDED_ASSEMBLER?: string;
  UPTIMER_SHARDED_FRAGMENT_SEED?: string;
  UPTIMER_SHARDED_PUBLISH?: string;
  UPTIMER_SCHEDULED_SHARDED_SKIP_HOMEPAGE_REFRESH?: string;
  UPTIMER_SCHEDULED_SHARDED_CONTINUATION?: string;
  UPTIMER_SHARDED_RUNTIME_UPDATE_BATCH_SIZE?: string;
  UPTIMER_SHARDED_ASSEMBLER_MODE?: string;
  UPTIMER_SHARDED_FRAGMENT_SEED_BATCH_SIZE?: string;
  UPTIMER_TRUST_SCHEDULED_RUNTIME_UPDATES?: string;
  UPTIMER_INTERNAL_SCHEDULED_BATCH_SIZE?: string;
  UPTIMER_INTERNAL_SCHEDULED_BATCH_CONCURRENCY?: string;
  UPTIMER_INTERNAL_SCHEDULED_CHECK_BATCH_TIMEOUT_MS?: string;
  UPTIMER_INTERNAL_CHECK_BATCH_FRAGMENT_WRITE_SPLIT?: string;
  UPTIMER_INTERNAL_CHECK_BATCH_TRUST_SCHEDULER_LEASE?: string;
  UPTIMER_SCHEDULED_REFRESH_LOGS?: string;

  // 管理端点的内存级、实例级速率限制。
  // 保持为可选，以免影响旧版部署。
  ADMIN_RATE_LIMIT_MAX?: string;
  ADMIN_RATE_LIMIT_WINDOW_SEC?: string;
}
